#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "minijava/lexer"
require "minijava/syntax"
require "active_support/core_ext/module/delegation"

module MiniJava
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 118)
delegate :next_token, :line, to: :@lexer

def self.program_from(source)
  new(source).program
end

def initialize(source)
  @lexer   = MiniJava::Lexer.new(source)
  @yydebug = !ENV["DEBUG"].nil?
end

def on_error(*)
  $stderr.puts "Parse error on line #{line}"
end

alias_method :program, :do_parse
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    62,    36,   127,    39,    62,    98,    29,    30,     7,    62,
    99,    29,    30,    11,    58,    29,    30,    37,    58,     7,
   108,    62,   109,    58,     7,    17,    10,    59,     7,    60,
    61,    59,    18,    60,    61,    58,    59,     7,    60,    61,
     7,     7,    62,    68,    29,    30,     7,    62,    59,   110,
    60,    61,    67,   108,    68,   109,    58,     7,     7,    62,
     7,    58,     7,    67,   101,    54,    29,    30,     7,    59,
    89,    60,    61,    58,    59,    88,    60,    61,    89,     7,
    50,    49,    48,    88,     7,    89,    59,   151,    60,    61,
    88,   108,    89,   109,    47,   107,     7,    88,    46,    44,
    43,    83,    84,    86,    87,    91,     7,   120,    42,    83,
    84,    86,    87,    91,     7,    40,    83,    84,    86,    87,
    91,     7,    33,    83,    84,    86,    87,    91,     7,    89,
    32,    25,    24,   129,    88,    89,   130,     7,   132,    20,
    88,    89,    19,   135,     3,   138,    88,    89,    16,   140,
    14,   142,    88,    89,   143,   108,     7,   109,    88,   107,
    83,    84,    86,    87,    91,     7,    83,    84,    86,    87,
    91,     7,    83,    84,    86,    87,    91,     7,    83,    84,
    86,    87,    91,     7,    83,    84,    86,    87,    91,     7,
    89,     4,    12,     8,     7,    88,    89,    75,    74,     7,
    73,    88,    89,    72,    66,    94,    65,    88,    89,    64,
    63,   nil,   nil,    88,    89,   nil,   nil,   nil,   nil,    88,
   nil,    83,    84,    86,    87,    91,     7,    83,    84,    86,
    87,    91,     7,    83,    84,    86,    87,    91,     7,    83,
    84,    86,    87,    91,     7,    83,    84,    86,    87,    91,
     7,    89,   nil,   nil,   nil,   nil,    88,    89,   nil,   nil,
   nil,   nil,    88,    89,   nil,   nil,   nil,   nil,    88,    89,
   117,   108,   nil,   109,    88,   107,   105,   106,   104,   103,
   nil,   nil,    83,    84,    86,    87,    91,     7,    83,    84,
    86,    87,    91,     7,    83,    84,    86,    87,    91,     7,
    83,    84,    86,    87,    91,     7,   108,   nil,   109,   nil,
   107,   105,   106,   104,   103,   108,   nil,   109,   nil,   107,
   105,   106,   104,   103,   nil,   nil,   nil,   nil,   nil,   150,
   nil,   108,   nil,   109,   114,   107,   105,   106,   104,   103,
   108,   nil,   109,   nil,   107,   105,   106,   104,   103,   nil,
   102,   nil,   nil,   nil,   nil,   131,   108,   nil,   109,   148,
   107,   105,   106,   104,   103,   118,   108,   nil,   109,   nil,
   107,   105,   106,   104,   103,   116,   108,   nil,   109,   nil,
   107,   105,   106,   104,   103,   108,   137,   109,   nil,   107,
   105,   106,   104,   103,   108,   115,   109,   nil,   107,   105,
   106,   104,   103,   108,   147,   109,   nil,   107,   105,   106,
   104,   103,   108,   nil,   109,   nil,   107,   105,   106,   104,
   108,   nil,   109,   nil,   107,   105,   106 ]

racc_action_check = [
   142,    26,   109,    28,   120,    76,    37,    37,   109,   117,
    78,    22,    22,     5,   142,    64,    64,    26,   120,    37,
   125,   116,   125,   117,    22,    13,     5,   142,    64,   142,
   142,   120,    13,   120,   120,   116,   117,   142,   117,   117,
    28,   120,    51,    70,    99,    99,   117,    58,   116,    87,
   116,   116,    70,   112,    56,   112,    51,    99,   116,    57,
    79,    58,    87,    56,    80,    50,    51,    51,    45,    51,
    66,    51,    51,    57,    58,    66,    58,    58,   150,    51,
    42,    41,    40,   150,    58,   138,    57,   145,    57,    57,
   138,   123,   132,   123,    39,   123,    57,   132,    38,    36,
    35,    66,    66,    66,    66,    66,    66,   101,    33,   150,
   150,   150,   150,   150,   150,    29,   138,   138,   138,   138,
   138,   138,    24,   132,   132,   132,   132,   132,   132,   129,
    23,    21,    20,   110,   129,   108,   111,    18,   115,    16,
   108,   107,    15,   118,     0,   128,   107,   106,    12,   130,
    11,   133,   106,   105,   136,   124,    10,   124,   105,   124,
   129,   129,   129,   129,   129,   129,   108,   108,   108,   108,
   108,   108,   107,   107,   107,   107,   107,   107,   106,   106,
   106,   106,   106,   106,   105,   105,   105,   105,   105,   105,
   104,     1,     6,     4,     3,   104,   103,    62,    61,    65,
    60,   103,    89,    59,    55,    71,    54,    89,    88,    53,
    52,   nil,   nil,    88,    74,   nil,   nil,   nil,   nil,    74,
   nil,   104,   104,   104,   104,   104,   104,   103,   103,   103,
   103,   103,   103,    89,    89,    89,    89,    89,    89,    88,
    88,    88,    88,    88,    88,    74,    74,    74,    74,    74,
    74,    73,   nil,   nil,   nil,   nil,    73,    72,   nil,   nil,
   nil,   nil,    72,    68,   nil,   nil,   nil,   nil,    68,    67,
    96,    96,   nil,    96,    67,    96,    96,    96,    96,    96,
   nil,   nil,    73,    73,    73,    73,    73,    73,    72,    72,
    72,    72,    72,    72,    68,    68,    68,    68,    68,    68,
    67,    67,    67,    67,    67,    67,   144,   nil,   144,   nil,
   144,   144,   144,   144,   144,    92,   nil,    92,   nil,    92,
    92,    92,    92,    92,   nil,   nil,   nil,   nil,   nil,   144,
   nil,    81,   nil,    81,    92,    81,    81,    81,    81,    81,
   141,   nil,   141,   nil,   141,   141,   141,   141,   141,   nil,
    81,   nil,   nil,   nil,   nil,   113,   113,   nil,   113,   141,
   113,   113,   113,   113,   113,    97,    97,   nil,    97,   nil,
    97,    97,    97,    97,    97,    95,    95,   nil,    95,   nil,
    95,    95,    95,    95,    95,   126,   126,   126,   nil,   126,
   126,   126,   126,   126,    93,    93,    93,   nil,    93,    93,
    93,    93,    93,   139,   139,   139,   nil,   139,   139,   139,
   139,   139,   121,   nil,   121,   nil,   121,   121,   121,   121,
   122,   nil,   122,   nil,   122,   122,   122 ]

racc_action_pointer = [
   130,   191,   nil,   156,   193,    12,   177,   nil,   nil,   nil,
   118,   134,   131,    10,   nil,   126,   121,   nil,    99,   nil,
   113,   115,   -14,   115,   102,   nil,     0,   nil,     2,   111,
   nil,   nil,   nil,   106,   nil,    85,    83,   -19,    75,    71,
    77,    65,    59,   nil,   nil,    30,   nil,   nil,   nil,   nil,
    61,    41,   194,   207,   201,   180,    50,    58,    46,   201,
   198,   196,   174,   nil,   -10,   161,    68,   267,   261,   nil,
    39,   189,   255,   249,   212,   nil,     2,   nil,   -17,    22,
    61,   327,   nil,   nil,   nil,   nil,   nil,    24,   206,   200,
   nil,   nil,   311,   390,   nil,   372,   267,   362,   nil,    19,
   nil,    92,   nil,   194,   188,   151,   145,   139,   133,   -30,
   129,   134,    49,   352,   nil,   125,    20,     8,   120,   nil,
     3,   408,   416,    87,   151,    16,   381,   nil,   143,   127,
   146,   nil,    90,   122,   nil,   nil,   138,   nil,    83,   399,
   nil,   336,    -1,   nil,   302,    84,   nil,   nil,   nil,   nil,
    76,   nil,   nil ]

racc_action_default = [
   -62,   -62,    -4,   -62,   -62,    -1,   -62,   -61,   153,    -5,
   -62,   -62,   -62,   -62,    -8,   -62,   -62,   -10,   -62,    -2,
   -62,   -62,   -14,   -62,   -62,    -6,    -9,   -11,   -62,   -22,
   -21,   -23,   -10,   -62,   -15,   -62,   -62,   -62,   -62,   -62,
   -62,   -62,   -62,   -10,   -17,   -62,   -12,   -13,   -20,    -7,
   -62,   -29,   -62,   -62,   -62,   -62,   -23,   -29,   -29,   -62,
   -62,   -62,   -62,   -16,   -24,   -62,   -62,   -62,   -62,   -30,
   -62,   -62,   -62,   -62,   -62,   -37,   -62,   -25,   -26,   -62,
   -62,   -62,   -46,   -47,   -48,   -49,   -50,   -62,   -62,   -62,
   -59,   -60,   -62,   -62,   -31,   -62,   -62,   -62,   -18,   -62,
   -28,   -62,   -19,   -62,   -62,   -62,   -62,   -62,   -62,   -62,
   -62,   -62,   -53,   -62,   -35,   -62,   -62,   -62,   -62,   -27,
   -62,   -38,   -39,   -40,   -41,   -42,   -62,   -44,   -62,   -62,
   -62,   -54,   -62,   -62,   -33,   -34,   -62,   -43,   -55,   -62,
   -52,   -62,   -62,    -3,   -57,   -62,   -56,   -51,   -36,   -32,
   -62,   -45,   -58 ]

racc_goto_table = [
     6,    45,    55,    77,   146,    21,    51,    13,    69,    71,
    26,    15,    34,   133,   134,    23,   152,   136,    35,    31,
    41,    52,    76,     5,     2,    38,   145,     9,    79,    81,
    92,    93,     1,   nil,    31,    95,    96,    97,   119,   149,
   nil,   nil,    53,   nil,   nil,   nil,   nil,   nil,    56,   nil,
   nil,   112,   113,   nil,    70,    70,   nil,   nil,   nil,   nil,
   nil,    31,    80,    79,   nil,   nil,   121,   122,   123,   124,
   125,   126,   nil,   nil,   nil,   nil,   100,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   111,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   139,   nil,   nil,   141,    31,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   128,   nil,   nil,   nil,
   nil,   nil,   nil,    70,    70,   nil,   nil,    70,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    70 ]

racc_goto_check = [
     4,    12,    17,    19,    23,     8,     9,     4,    17,    17,
    10,     5,    13,     6,     6,     4,    23,     6,    14,     4,
     8,    15,    16,     3,     2,     4,    21,     7,    12,    18,
    18,    18,     1,   nil,     4,    18,    18,    18,    19,     6,
   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,     4,   nil,
   nil,    18,    18,   nil,     4,     4,   nil,   nil,   nil,   nil,
   nil,     4,     4,    12,   nil,   nil,    18,    18,    18,    18,
    18,    18,   nil,   nil,   nil,   nil,     4,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    18,   nil,   nil,    18,     4,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     4,   nil,   nil,   nil,
   nil,   nil,   nil,     4,     4,   nil,   nil,     4,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,    32,    24,    21,    -3,    -1,  -103,    22,   -12,   -37,
   -12,   nil,   -36,   -14,    -8,   -22,   -42,   -49,   -37,   -61,
   nil,  -112,   nil,  -134,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,    85,   nil,    57,   nil,   nil,    22,
   nil,    27,    28,   nil,   nil,   nil,   nil,   nil,   144,   nil,
    78,   nil,    82,   nil,    90 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 40, :_reduce_1,
  5, 41, :_reduce_2,
  13, 44, :_reduce_3,
  0, 42, :_reduce_4,
  2, 42, :_reduce_5,
  5, 46, :_reduce_6,
  7, 46, :_reduce_7,
  2, 46, :_reduce_8,
  2, 47, :_reduce_9,
  0, 48, :_reduce_10,
  2, 48, :_reduce_11,
  3, 50, :_reduce_12,
  3, 50, :_reduce_13,
  0, 49, :_reduce_14,
  2, 49, :_reduce_15,
  4, 52, :_reduce_16,
  2, 52, :_reduce_17,
  6, 53, :_reduce_18,
  5, 54, :_reduce_19,
  3, 51, :_reduce_20,
  1, 51, :_reduce_21,
  1, 51, :_reduce_22,
  1, 51, :_reduce_23,
  0, 55, :_reduce_24,
  1, 55, :_reduce_25,
  1, 58, :_reduce_26,
  3, 58, :_reduce_27,
  2, 59, :_reduce_28,
  0, 56, :_reduce_29,
  2, 56, :_reduce_30,
  3, 45, :_reduce_31,
  7, 45, :_reduce_32,
  5, 45, :_reduce_33,
  5, 45, :_reduce_34,
  4, 45, :_reduce_35,
  7, 45, :_reduce_36,
  2, 45, :_reduce_37,
  3, 57, :_reduce_38,
  3, 57, :_reduce_39,
  3, 57, :_reduce_40,
  3, 57, :_reduce_41,
  3, 57, :_reduce_42,
  4, 57, :_reduce_43,
  3, 57, :_reduce_44,
  6, 57, :_reduce_45,
  1, 57, :_reduce_46,
  1, 57, :_reduce_47,
  1, 57, :_reduce_48,
  1, 57, :_reduce_49,
  1, 57, :_reduce_50,
  5, 57, :_reduce_51,
  4, 57, :_reduce_52,
  2, 57, :_reduce_53,
  3, 57, :_reduce_54,
  0, 60, :_reduce_55,
  1, 60, :_reduce_56,
  1, 62, :_reduce_57,
  3, 62, :_reduce_58,
  1, 61, :_reduce_59,
  1, 63, :_reduce_60,
  1, 43, :_reduce_61 ]

racc_reduce_n = 62

racc_shift_n = 153

racc_token_table = {
  false => 0,
  :error => 1,
  :LPAREN => 2,
  :RPAREN => 3,
  :LBRACKET => 4,
  :RBRACKET => 5,
  :DOT => 6,
  :NOT => 7,
  :STAR => 8,
  :PLUS => 9,
  :MINUS => 10,
  :LT => 11,
  :AND => 12,
  :EQUAL => 13,
  :CLASS => 14,
  :LBRACE => 15,
  :RBRACE => 16,
  :PUBLIC => 17,
  :STATIC => 18,
  :VOID => 19,
  :MAIN => 20,
  :STRING => 21,
  :EXTENDS => 22,
  :SEMICOLON => 23,
  :RETURN => 24,
  :INT => 25,
  :BOOLEAN => 26,
  :COMMA => 27,
  :IF => 28,
  :ELSE => 29,
  :WHILE => 30,
  :PRINTLN => 31,
  :LENGTH => 32,
  :TRUE => 33,
  :FALSE => 34,
  :THIS => 35,
  :NEW => 36,
  :DECIMAL_NUMERAL => 37,
  :IDENTIFIER => 38 }

racc_nt_base = 39

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "NOT",
  "STAR",
  "PLUS",
  "MINUS",
  "LT",
  "AND",
  "EQUAL",
  "CLASS",
  "LBRACE",
  "RBRACE",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "EXTENDS",
  "SEMICOLON",
  "RETURN",
  "INT",
  "BOOLEAN",
  "COMMA",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTLN",
  "LENGTH",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "DECIMAL_NUMERAL",
  "IDENTIFIER",
  "$start",
  "Program",
  "MainClassDeclaration",
  "ClassDeclarations",
  "Identifier",
  "MainMethodDeclaration",
  "Statement",
  "ClassDeclaration",
  "ClassBody",
  "VariableDeclarations",
  "MethodDeclarations",
  "VariableDeclaration",
  "Type",
  "MethodDeclaration",
  "MethodSignature",
  "MethodBody",
  "FormalParameters",
  "Statements",
  "Expression",
  "OneOrMoreFormalParameters",
  "FormalParameter",
  "ActualParameters",
  "IntegerLiteral",
  "OneOrMoreActualParameters",
  "DecimalNumeral" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 17)
  def _reduce_1(val, _values)
     MiniJava::Syntax::Program.new(val[0], val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 20)
  def _reduce_2(val, _values)
     MiniJava::Syntax::MainClassDeclaration.new(val[1], val[3]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 25)
  def _reduce_3(val, _values)
     MiniJava::Syntax::MainMethodDeclaration.new(val[8], val[11]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_4(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_5(val, _values)
     val[0].append(val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 30)
  def _reduce_6(val, _values)
     MiniJava::Syntax::ClassDeclaration.new(val[1], *val[3]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 32)
  def _reduce_7(val, _values)
     MiniJava::Syntax::SubclassDeclaration.new(val[1], val[3], *val[5]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 33)
  def _reduce_8(val, _values)
     MiniJava::Syntax::InvalidClassDeclaration.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 34)
  def _reduce_9(val, _values)
     [ val[0], val[1] ] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_10(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_11(val, _values)
     val[0].append(val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 38)
  def _reduce_12(val, _values)
     MiniJava::Syntax::VariableDeclaration.new(val[0], val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_13(val, _values)
     MiniJava::Syntax::InvalidVariableDeclaration.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 41)
  def _reduce_14(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 41)
  def _reduce_15(val, _values)
     val[0].append(val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 45)
  def _reduce_16(val, _values)
     MiniJava::Syntax::MethodDeclaration.new(*val[0], *val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 47)
  def _reduce_17(val, _values)
     MiniJava::Syntax::InvalidMethodDeclaration.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 48)
  def _reduce_18(val, _values)
     [ val[1], val[2], val[4] ] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 52)
  def _reduce_19(val, _values)
     [ val[0], val[1], val[3] ] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 55)
  def _reduce_20(val, _values)
     MiniJava::Syntax::ArrayType.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 56)
  def _reduce_21(val, _values)
     MiniJava::Syntax::BooleanType.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 57)
  def _reduce_22(val, _values)
     MiniJava::Syntax::IntegerType.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 58)
  def _reduce_23(val, _values)
     MiniJava::Syntax::IdentifierType.new(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_24(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_25(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 63)
  def _reduce_26(val, _values)
     [ val[0] ] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_27(val, _values)
     val[1].prepend(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 66)
  def _reduce_28(val, _values)
     MiniJava::Syntax::FormalParameter.new(val[0], val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_29(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_30(val, _values)
     val[1].prepend(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_31(val, _values)
     MiniJava::Syntax::Block.new(val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 72)
  def _reduce_32(val, _values)
     MiniJava::Syntax::IfStatement.new(val[2], val[4], val[6]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 73)
  def _reduce_33(val, _values)
     MiniJava::Syntax::WhileStatement.new(val[2], val[4]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_34(val, _values)
     MiniJava::Syntax::PrintStatement.new(val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 75)
  def _reduce_35(val, _values)
     MiniJava::Syntax::Assignment.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 77)
  def _reduce_36(val, _values)
     MiniJava::Syntax::ArrayAssignment.new(val[0], val[2], val[5]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_37(val, _values)
     MiniJava::Syntax::InvalidStatement.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_38(val, _values)
     MiniJava::Syntax::And.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 82)
  def _reduce_39(val, _values)
     MiniJava::Syntax::LessThan.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 83)
  def _reduce_40(val, _values)
     MiniJava::Syntax::Plus.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 84)
  def _reduce_41(val, _values)
     MiniJava::Syntax::Minus.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_42(val, _values)
     MiniJava::Syntax::Times.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_43(val, _values)
     MiniJava::Syntax::ArraySubscript.new(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 87)
  def _reduce_44(val, _values)
     MiniJava::Syntax::ArrayLength.new(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 88)
  def _reduce_45(val, _values)
     MiniJava::Syntax::Call.new(val[0], val[2], val[4]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 89)
  def _reduce_46(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 90)
  def _reduce_47(val, _values)
     MiniJava::Syntax::TrueLiteral.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 91)
  def _reduce_48(val, _values)
     MiniJava::Syntax::FalseLiteral.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 92)
  def _reduce_49(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_50(val, _values)
     MiniJava::Syntax::This.instance 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 94)
  def _reduce_51(val, _values)
     MiniJava::Syntax::NewArray.new(val[3]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 95)
  def _reduce_52(val, _values)
     MiniJava::Syntax::NewObject.new(val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 96)
  def _reduce_53(val, _values)
     MiniJava::Syntax::Not.new(val[1]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 97)
  def _reduce_54(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 99)
  def _reduce_55(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 99)
  def _reduce_56(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 102)
  def _reduce_57(val, _values)
     [ val[0] ] 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 103)
  def _reduce_58(val, _values)
     val[1].prepend(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 105)
  def _reduce_59(val, _values)
     MiniJava::Syntax::IntegerLiteral.new(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 106)
  def _reduce_60(val, _values)
     Integer(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 108)
  def _reduce_61(val, _values)
     MiniJava::Syntax::Identifier.new(val[0]) 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module MiniJava
