name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Install dependencies
        run: gem install bundler --force && bundle install --jobs 4 --retry 3

      - name: Test
        run: bundle exec rake
